/**
 * author: balaji-xubuntu
 *
 * Problem:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
 * even-valued terms.
 */
object Problem2 {
	var sum = 2
	def main(args : Array[String]){
		println(1)
		println(2)
		println("sum: "+generateFibonacciSum(1,2))
	}

	def generateFibonacciSum(i : Int, j : Int) : Int = {
		val k = i + j
		println(k+","+sum)
		if (k > 4000000)    sum
		else{
			if (k % 2 == 0) sum = sum + k
			generateFibonacciSum(j , k)
		}
	}

}
